name: Test CI

on: [push]

env:
  DATABRICKS_HOST: "https://dbc-147abc45-b6c7.cloud.databricks.com"
  DATABRICKS_TOKEN: "dapia756ad5e7ea2698af48c80e1eb1e6563"
  FABRIC_NAME: "dev"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      # Install all python dependencies 
      # prophecy-libs not included here because prophecy-build-tool 
      # takes care of it by reading each pipeline's setup.py
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pytest wheel pytest-html pyspark  prophecy-build-tool-test==1.0.4.9
      - name: Run PBT build
        run: pbt build --path .
      - name: Run PBT test
        run: pbt test --path .
      - name: Run PBT deploy
        run: pbt deploy --path .
